name:  ci-cd
on:
  workflow_dispatch:
  push:

jobs:
  cipipeline:
    name: ci-pipeline
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - shell: bash
      run: |
        npm ci
        npm run prettier
        npm run typecheck
        npm run test
        npm run build
    - uses: actions/upload-pages-artifact@v3
      with:
        path: dist

  cdpipeline:
    name: cd-pipeline
    runs-on: ubuntu-latest
    needs: cipipeline
    permissions:
        pages: write
        id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    outputs:
      pages-url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      - name: Output env url
        run: echo ${{ env.url }}
    
  smoke-test:
    needs: cdpipeline
    runs-on: ubuntu-latest
    timeout-minutes: 3
    strategy:
      matrix:
        browsers: ["firefox", "chromium"]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
  
      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install ${{ matrix.browser }}

      - name: Run Playwright tests
        run: npx playwright test --project ${{ matrix.browser }}
        env:
          PLAYWRIGHT_BASE_URL: ${{ needs.cdpipeline.outputs.page_url }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.browser }}
          path: playwright-report/
          retention-days: 1
